# Adapted from https://github.com/numba/numba/blob/master/azure-pipelines.yml
jobs:
# Mac and Linux could potentially use the same template
# except it isn't clear how to use a different build matrix
# for each, so for now they are separate
- template: ci/azure/macos.yml
  parameters:
    name: macOS
    vmImage: xcode9-macos10.13
# - template: ci/azure/linux.yml
#   parameters:
#     name: Linux
#     vmImage: ubuntu-16.04

# Windows Python 2.7 needs VC 9.0 installed, and not sure
# how to make that a conditional task, so for now these are
# separate templates as well
- template: ci/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
- template: ci/azure/windows-py27.yml
  parameters:
    name: WindowsPy27
    vmImage: vs2017-win2016

- job: 'Code_checks'
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - script: python -m pip install flake8
    displayName: 'Installing flake8'

  - script: python -m pip install cpplint
    displayName: 'Installing cpplint'
    condition: true

  - script: AZURE=true ci/code_checks.sh lint
    displayName: 'Linting'
    condition: true

  - script: AZURE=true ci/code_checks.sh patterns
    displayName: 'Looking for unwanted patterns'
    condition: true

  - script: ci/code_checks.sh doctests
    displayName: 'Running doctests'
    condition: true
