version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-{{ .Branch }}-
      # - run:
      #     name: "Install Python3"
      #     command: |
      #       apk add --no-cache \
      #         python3 \
      #         libc-dev \
      #         gcc
      - run:
          name: "Test aws"
          working_directory: ~/project/aws
          command: |
            python3.7 -m venv .venv;
            . .venv/bin/activate
            pip install -U pip
            pip install -U -r requirements.txt
            nose2
            python setup.py test
      - save_cache: &save_cache
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/project/aws/.venv
            - ~/project/database/.venv
            - ~/project/deployment/.venv
            - ~/.cache/pip
