main:
  templates_path: _templates
  base_template: "layout.html"
  ignore:
  - _templates/layout.html
  - config.yml
  - try.md  # the binder page will be added later
  github_repo_url: pandas-dev/pandas
  context_preprocessors:
  - pandas_web.Preprocessors.current_year
  - pandas_web.Preprocessors.navbar_add_info
  - pandas_web.Preprocessors.blog_add_posts
  - pandas_web.Preprocessors.maintainers_add_info
  - pandas_web.Preprocessors.home_add_releases
  - pandas_web.Preprocessors.roadmap_pdeps
  markdown_extensions:
  - toc
  - tables
  - fenced_code
  - meta
static:
  logo: /static/img/pandas_white.svg
  css:
  - /static/css/pandas.css
navbar:
  - name: "About us"
    target:
    - name: "About pandas"
      target: /about/
    - name: "Project roadmap"
      target: /about/roadmap.html
    - name: "Governance"
      target: /about/governance.html
    - name: "Team"
      target: /about/team.html
    - name: "Sponsors"
      target: /about/sponsors.html
    - name: "Citing and logo"
      target: /about/citing.html
  - name: "Getting started"
    target: /getting_started.html
  - name: "Documentation"
    target: /docs/
  - name: "Community"
    target:
    - name: "Blog"
      target: /community/blog/
    - name: "Ask a question (StackOverflow)"
      target: https://stackoverflow.com/questions/tagged/pandas
    - name: "Code of conduct"
      target: /community/coc.html
    - name: "Ecosystem"
      target: /community/ecosystem.html
  - name: "Contribute"
    target: /contribute.html
blog:
  num_posts: 50
  posts_path: community/blog
  author: "pandas team"
  feed_name: "pandas blog"
  feed:
  - https://wesmckinney.com/feeds/pandas.atom.xml
  - https://tomaugspurger.github.io/feed
  - https://jorisvandenbossche.github.io/feeds/pandas.atom.xml
  - https://datapythonista.me/blog/feeds/pandas.atom.xml
  - https://numfocus.org/tag/pandas/feed/
maintainers:
  active:
  - wesm
  - jorisvandenbossche
  - TomAugspurger
  - jreback
  - gfyoung
  - WillAyd
  - mroeschke
  - jbrockmendel
  - datapythonista
  - simonjayhawkins
  - topper-123
  - alimcmaster1
  - bashtage
  - Dr-Irv
  - MarcoGorelli
  - rhshadrach
  - phofl
  - attack68
  - fangchenli
  - twoertwein
  - lithomas1
  - mzeitlin11
  - lukemanley
  inactive:
  - lodagro
  - jseabold
  - jtratner
  - shoyer
  - chris-b1
  - sinhrks
  - cpcloud
  - toobaz
  - jschendel
  - charlesdong1991
  - dsaxton
  coc:
  - Bijay Regmi
  - Wuraola Oyewusi
  - Мария Чакчурина
  - Tom Augspurger
  numfocus:
  - Wes McKinney
  - Jeff Reback
  - Joris Van den Bossche
  - Tom Augspurger
  - Matthew Roeschke
sponsors:
  active:
  - name: "NumFOCUS"
    url: https://numfocus.org/
    logo: /static/img/partners/numfocus.svg
    kind: numfocus
  - name: "Two Sigma"
    url: https://www.twosigma.com/
    logo: /static/img/partners/two_sigma.svg
    kind: partner
    description: "Jeff Reback"
  - name: "Voltron Data"
    url: https://voltrondata.com/
    logo: /static/img/partners/voltron_data.svg
    kind: partner
    description: "Joris Van den Bossche"
  - name: "d-fine GmbH"
    url: https://www.d-fine.com/en/
    logo: /static/img/partners/dfine.svg
    kind: partner
    description: "Patrick Hoefler"
  - name: "Quansight"
    url: https://quansight.com/
    logo: /static/img/partners/quansight_labs.svg
    kind: partner
    description: "Marco Gorelli"
  - name: "Nvidia"
    url: https://www.nvidia.com
    logo: /static/img/partners/nvidia.svg
    kind: partner
    description: "Matthew Roeschke"
  - name: "Tidelift"
    url: https://tidelift.com
    logo: /static/img/partners/tidelift.svg
    kind: regular
    description: "<i>pandas</i> is part of the <a href=\"https://tidelift.com/subscription/pkg/pypi-pandas?utm_source=pypi-pandas&utm_medium=referral&utm_campaign=readme\">Tidelift subscription</a>. You can support pandas by becoming a Tidelift subscriber."
  - name: "Chan Zuckerberg Initiative"
    url: https://chanzuckerberg.com/
    logo: /static/img/partners/czi.svg
    kind: regular
    description: "<i>pandas</i> is funded by the Essential Open Source Software for Science program of the Chan Zuckerberg Initiative. The funding is used for general maintenance, improve extension types, and a efficient string type."
  - name: "Bodo"
    url: https://www.bodo.ai/
    logo: /static/img/partners/bodo.svg
    kind: regular
    description: "Bodo's parallel computing platform uses pandas API, and Bodo financially supports pandas development to help improve pandas, in particular the pandas API"
  inkind:  # not included in active so they don't appear in the home page
  - name: "OVH"
    url: https://us.ovhcloud.com/
    description: "Website and documentation hosting."
  - name: "Indeed"
    url: https://opensource.indeedeng.io/
    description: "<i>pandas</i> logo design"
  past:
  - name: "Paris-Saclay Center for Data Science"
    url: https://www.datascience-paris-saclay.fr/
    kind: partner
  - name: "Anaconda"
    url: https://www.anaconda.com/
    kind: partner
  - name: "RStudio"
    url: https://www.rstudio.com/
    kind: partner
  - name: "Ursa Labs"
    url: https://ursalabs.org/
    kind: partner
  - name: "Gousto"
    url: https://www.gousto.co.uk/
    kind: partner
roadmap:
  pdeps_path: pdeps
