name: pandas
channels:
  - defaults
  - conda-forge
dependencies:
  - blosc
  - bottleneck
  - fastparquet
  - feather-format
  - matplotlib
  - numexpr
  - numpy=1.13*
  - openpyxl=2.5.5
  - pyarrow
  - pytables
  - python-dateutil
  - python=3.6.*
  - pytz
  - scipy
  - thrift=0.10*
  - xlrd
  - xlsxwriter
  - xlwt
  # universal
  - cython
  - pytest
  - pytest-xdist
