name: pandas
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4
  - bottleneck
  - dateutil
  - gcsfs
  - html5lib
  - jinja2=2.8
  - lxml
  - matplotlib
  - numexpr
  - numpy=1.12*
  - openpyxl
  - pytables
  - python=2.7.*
  - pytz
  - s3fs
  - scipy
  - sqlalchemy
  - xlrd
  - xlsxwriter
  - xlwt
  # universal
  - cython>=0.28.2
  - pytest
  - pytest-xdist
  - moto
  - hypothesis
