name: pandas
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4
  - bottleneck
  - dateutil
  - html5lib
  - jinja2=2.8
  - lxml
  - matplotlib
  - numexpr
  - numpy=1.10*
  - openpyxl=2.5.5
  - pytables==3.2.2
  - python=2.7.*
  - pytz
  - s3fs
  - scipy
  - sqlalchemy
  - xlrd
  - xlsxwriter
  - xlwt
  # universal
  - cython
  - pytest
  - pytest-xdist
  - moto
