name: "AutoCodeRover Bot"

permissions:
  issues: write
  contents: write # change to `read` if you do not want to use open-pr
  pull-requests: write # (optional) remove if you do not want to use open-pr

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  acr-bot:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body || github.event.issue.body, '@acr-bot') }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - id: set-var
        run: echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_OUTPUT

      - name: ACR bot
        uses: AutoCodeRoverSG/code-rover-bot@v2.0.0
        env:
          TARGET_REPO_PATH: ${{ steps.set-var.outputs.GITHUB_WORKSPACE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
